language: node_js

node_js:
  - "stable"

branches:
  only:
    - "version-2"

cache:
  directories:
    - "node_modules"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - npm test
  - npm run codacy