language: node_js
node_js:
  - stable
  - 10.3.0
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      env: KARMA_REPORTER=dots
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - npm ci
      script:
        - npm test
        - npm run codacy
    - stage: build
      script:
        - npm run build
    - stage: deploy
      name: "Deploy Package to NPM"
      node_js: stable
      script: skip
      deploy:
        provider: npm
        email: quangdaon@gmail.com
        api_key:
          secure: P1AKEqheATbMml0reT5Bl1CDU/xioOS25N0GAnLmI9Nukp756FbhJv72uEckH1FKDYUas/oouXrnQCGfS6A7OXSjRILNtC9m+GyJDowmevqCxaJoGD0ZoioI1BLYNaw6Qaq6gFtzJ205UZWnOHPkOn5PX5PHnvRO2wOJKmjZdvo1dtIGFvqfQXyy/TvFf1egI5Xu22v7eUcDShuX7OKGLqW3nHGg0y/2Sg2EHdUzFdHZ8bTxS1MDv2V9IyCUNz45Xo90KCsFnM5cZ3oYuNb8wEbTZBc4iKiUUxRAMe7j35HcXTbHh+UaNzaBoROqdOzhgWm6VlTbPdkb6XvBoaGoAcpgluiUkxRxCX6Eby7Mx/E8y9FoMXTZaYL71A21ukeT+wfrMjqNqOQK2Ob8JcROH/m1BSh82CfZ23dST/88O5Uac8KJ/PmOj/FwawOzPIKd/XvYiJrKKjc0sDouu+MJA/fsFfdw13+/sQHfPd3YG42uf9aJNWwwoREaH6c9RxMil8e8Vsf8uh63NkQLcXob6DRe+ksldsWfeYFmad0Qtrl/k+K/eHTLt0GbuO2hvcg9CH+vN3pGka8MEfjWCuedtgrZEDOVAH1EZew1mdqFi+kNJ8ZBLWVQycak57bjjvtYRo+o7ncUX8JcCOvWq4MrdZ9hV2haLhHnxCRz8bCxvnM=
        on:
          tags: true
          repo: quangdaon/unlockjs
    - stage: docs
      name: "Deploy Documentation"
      node_js: stable
      env:
        global:
          - GH_USER="quangdaon"
          - GH_EMAIL="quangdaon@gmail.com"
          - DOC_REPO="quangdaon.github.io"
          - DOC_FOLDER_NAME="unlockjs"
          - DOC_FILES="docs/*"
          - DOC_REPO_URL="github.com/${GH_USER}/${DOC_REPO}.git"
          - secure: DVqCHEk2u2JrGXN628DecZPf0xfYmhqXUtxarKDqb8DT3mmrbQVZJBepagudGETew1XXTwVO0rT9YUdWEcR4DkHSxnvZVhUYdKXooazVNcjRLwK4lm450EY3jgjC/8mzkS7e4TmI/LduJ7+L1rZ0vXn83lZGCWXshfXBqRjKiXBlkXjLnj0G0QZoIdJEySKFjR8AbD6UMGQ1zWkbyMJlcMHe5m/8FisQvRGFfmF0X8ag3aUhhj2teEZVHrNy9/Q/saLCoO7xPkyQDHkR3/3U4FUcs1yguoRH13kJMZPww3pwHnmjPnGETi4ltHvur8AHee8nxSfPMP2XDKaY/1Y25liWJx97TCN3vxs2525SnQPngqnx/8FEOxOVB78eJwZucXgsSB/+vjgMeM5DTT9yPtucn+2Kq68hcJBUzZsEPdsriU+NQG9uga+3xGn8Ptm9BEbRvaoWKcR5kuWF4wdpP/N0N+dExBjVBvk4WybONle4sScmz0s2C10YK/GZzXTG58YnteIRdLFHpXlCYmJeo1TQmOlwt7vhJp0YRKWLr6apBSmFRsy5dNWcEH+kiUsqwpvoQDhvX37D4mEn/rPE2HumxFF5u7/v9ODsdIr8Nf0ORIo09eDsL2CZ7X/1R0GK1Srv7JorWsHWx0t8orEA5BF7Jd5IaoIWT7sWA6LzJnI=
      script:
        - npm run docs
      after_success:
        - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
        - DOC_DESTINATION="${DOC_REPO}/${DOC_FOLDER_NAME}"
        - git clone git://${DOC_REPO_URL}
        - mkdir -p ${DOC_DESTINATION}
        - mv -f ${DOC_FILES} ${DOC_DESTINATION}
        - cd ${DOC_REPO}
        - git remote
        - git config user.email ${GH_EMAIL}
        - git config user.name ${GH_USER}
        - git add ${DOC_FOLDER_NAME}/*
        - git commit -m "${DOC_FOLDER_NAME} - ${MESSAGE}"
        - git push "https://${GITHUB_ACCESS_TOKEN}@${DOC_REPO_URL}" master
stages:
  - test
  - name: build
    if: tag IS present
  - name: deploy
    if: tag IS present
  - name: docs
    if: tag IS present
