language: node_js
node_js:
  - stable
  - 10.3.0
env:
  matrix: KARMA_REPORTER=dots
cache:
  directories:
    - node_modules
dist: xenial
services:
  - xvfb
before_script:
  - npm ci
script:
  - npm test
  - npm run codacy
jobs:
  include:
    - stage: deploy
      name: "Deploy Package to NPM"
      node_js: stable
      script:
        - npm run build
      deploy:
        provider: npm
        skip_cleanup: true
        email: quangdaon@gmail.com
        api_key:
          secure: P1AKEqheATbMml0reT5Bl1CDU/xioOS25N0GAnLmI9Nukp756FbhJv72uEckH1FKDYUas/oouXrnQCGfS6A7OXSjRILNtC9m+GyJDowmevqCxaJoGD0ZoioI1BLYNaw6Qaq6gFtzJ205UZWnOHPkOn5PX5PHnvRO2wOJKmjZdvo1dtIGFvqfQXyy/TvFf1egI5Xu22v7eUcDShuX7OKGLqW3nHGg0y/2Sg2EHdUzFdHZ8bTxS1MDv2V9IyCUNz45Xo90KCsFnM5cZ3oYuNb8wEbTZBc4iKiUUxRAMe7j35HcXTbHh+UaNzaBoROqdOzhgWm6VlTbPdkb6XvBoaGoAcpgluiUkxRxCX6Eby7Mx/E8y9FoMXTZaYL71A21ukeT+wfrMjqNqOQK2Ob8JcROH/m1BSh82CfZ23dST/88O5Uac8KJ/PmOj/FwawOzPIKd/XvYiJrKKjc0sDouu+MJA/fsFfdw13+/sQHfPd3YG42uf9aJNWwwoREaH6c9RxMil8e8Vsf8uh63NkQLcXob6DRe+ksldsWfeYFmad0Qtrl/k+K/eHTLt0GbuO2hvcg9CH+vN3pGka8MEfjWCuedtgrZEDOVAH1EZew1mdqFi+kNJ8ZBLWVQycak57bjjvtYRo+o7ncUX8JcCOvWq4MrdZ9hV2haLhHnxCRz8bCxvnM=
        on:
          tags: true
          repo: quangdaon/unlockjs
    - stage: docs
      name: "Deploy Documentation"
      node_js: stable
      env:
        - GH_USER="quangdaon"
        - GH_EMAIL="quangdaon@gmail.com"
        - DOC_REPO="unlockjs"
        - DOC_BRANCH="gh-pages"
        - DOC_FOLDER_NAME="docs"
        - DOC_REPO_URL="github.com/${GH_USER}/${DOC_REPO}.git"
        - secure: OYsX0V1Rtn/wVU8Fn3R7qpqPFZhAT2O+nvrHCCDD/fUVwQFMrRHyS0AjDMq7v+MTmrSozP7hMPaXFj/n9uRs903ekEnkILxwM5fLOwOdn/LO0c3RFIPSnpjkgTsePrl6Mnjvv1ary7PtisgmeD6ssP7dB5WbOJG1PZwqNZIlCb86ZdOVkjJk0+edfDAq5TuqwwjLLwULaTcMrG9Tv8p/nqTm4Gk44CbvM66Swydx0gwSEHYqQchnkJ6mh5HVnWI01AepfnNZ+OHX3ym20OHFLI+fMgACkFj610akYrE2sRxolXYKc4jpk2wb0oZ5sxQnSDOXEdUjSdRqCtitBatAyue4WSvrwWGiirQP1KZtw6Ve34PC/3TAmaeWN8sLltpof52uuE7CYxGorgZrygYlWRx7MHO9BPCiYqgqDwfMjrGmuiEnEIRsaPACIXbQQSJkxo3IARn+hBZIbNvchilS8ynr2HoiTHL+7r0pCQCo+yfIxlTSFVcxT634N15WzwwbNTveKV40Fdek2YBEH12XpsVbpzHuS0kG8IAylqPWBAQTcYP3hzQ41D5FVn3U2CxA4LhMZugRKTpVJac7LXmfLlixByf6pja8wWnoou4AXc+kbDh2xzWDQOgPeKQ0v9VvQKw9OXjgv7LLkuWcjpVXsVdlkPtOiD9mX7QKXyw38e4=
      script:
        - npm run docs
      after_success:
        - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
        - git remote
        - git config user.email ${GH_EMAIL}
        - git config user.name ${GH_USER}
        - git add ${DOC_FOLDER_NAME}/*
        - git commit -m "${DOC_REPO} - ${MESSAGE}" --force
        - git subtree push --prefix ${DOC_FOLDER_NAME} "https://${GITHUB_ACCESS_TOKEN}@${DOC_REPO_URL}" ${DOC_BRANCH}
stages:
  - test
  - name: deploy
    if: tag IS present
  - name: docs
