language: node_js
node_js:
- stable
- 8.4.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
script:
- npm test
- npm run codacy
- npm run build
deploy:
  provider: npm
  email: quangdaon@gmail.com
  api_key:
    secure: Np7Hrg5JMCupTAJTGu6onCyGilq+IyOLAMofgTj0sKDuDjrW68qfhC11lw7eERo7+MeKuQ2EYrnhDgNm/Yzl5e3xpMbmHma++oLZBGymVwpoLLVPJ3otY5Y4kXRV4xWGwKkpWdeV3QKXAQGae3eOI9/WStHsYXlSk9Oy4GAIp+bgy0HTpu8T961J72Yvt9FTE5AHqWTt7qo/J664OSO/FObbUuRq13RTxdunh+onHsLrXY6BhEkqXiOB1tGXb/HgWHA5vFoLXXJfCmUvmZ50WL+F/zFIIg0DoYBlBmdBqYj7K72AsP57f3OU38lw0e8JnjsWE7tP9hgEiR+lvqoElkzBNLmc6UATQOZjGGKc7JKlB9/J+s/m/JwIFGhoO8DgbP+KXFXcz9Ee04L/zlGJ7sSk7ztAILL37a4THQknB/WeonfPLE/Kh93HGrSeYjwDT8wdERhToEMrqlyC4CidfxqM8w2A8J2FjMHx/L9y+OtRL8XESP7EW6KPBsPzEPyAWI5WObioGXmFQx4iD81a5yjyIGRrcHZDTXdaV/JSJfbyk+gA6RG1SSW64zkWqfevLSKNopmlkcEU46p3nA4jIrQ+D99Erfnj8KUp7dO8bv0TbwmRue3+ZoFO4KwKWCjzFHrau8FJaWZKjyqSEtnhzbxvMEv3CPjslQVT761upH4=
  on:
    tags: true
    repo: quangdaon/unlockjs
    branch: master