name: NPM Publish
on:
  push:
    branches: [ release/2.0.0 ] # Change to main on release
    # tags:
    #   - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Run Tests
        run: npm test

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          dry-run: true # Remove on release
